apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userdb
  template:
    metadata:
      labels:
        app: userdb
    spec:
      containers:
        - name: userdb
          image: postgres:latest
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: user-env
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: user-env
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: userdb
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: userdb-volume
      volumes:
        - name: userdb-volume
          persistentVolumeClaim:
            claimName: user-pvc