apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
spec:
  selector:
    app: recommendation
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080