apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: user:1
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: user-env
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: user-env
                  key: POSTGRES_PASSWORD
          readinessProbe:
            httpGet:
              port: 8080
              path: /users
            initialDelaySeconds: 10
            periodSeconds: 2
            successThreshold: 5
            failureThreshold: 3