apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-pvc
spec:
  volumeName: user-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi